const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const SpritePlayer = require('./player.js');
const root = path.join(__dirname,'../output/universal');
const baseline = JSON.parse(fs.readFileSync(path.join(root,'sprites.json')));
const review = JSON.parse(fs.readFileSync(path.join(root,'review-sprites.json')));
const clip = review.animations.teeter;
assert.equal(clip.frameCount,4);assert.equal(clip.duration,1);assert.equal(clip.fps,4);assert.equal(clip.loop,true);
assert.equal(clip.authored,true);assert.equal(clip.variantOf,undefined);
assert.equal(clip.platformEdge.supportPixels,2*review.frameSize[0]/256);
assert.ok(fs.existsSync(path.join(root,clip.image)));
assert.deepEqual(review.pivot,baseline.pivot);
for(const [name,original] of Object.entries(baseline.animations))assert.deepEqual(review.animations[name],original);
const player = new SpritePlayer(review.animations,'teeter');
player.advance(1.125);assert.equal(player.playing,true);assert.equal(player.frameIndex,0);
player.advance(.125);assert.equal(player.frameIndex,1);
player.playSequence(['idle','teeter','idle'],false);
player.advance(baseline.animations.idle.duration*2+clip.duration+.01);assert.equal(player.finished,true);
console.log('PASS teeter timing, repetition, idle cuts, shared pivot and original clip preservation');
